### PR TITLE
Added books and new courses

### PR DESCRIPTION
**Pull request by PramodShenoy**

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
@PramodShenoy I've been working on improving Data Science, which has sadly had not been updated in years. (I've been the maintainer of the Computer Science curriculum for some time now) There are a lot of suggestions in this pull request! I would love to talk about these and hear how you chose this list. OSSU has a new Discord server, if you're available to talk you can often find me there. https://discord.gg/tgfXKzZ

**Comment by oNjEncUREn** [comment]
This pull request is over 3 years old.  We either need to merge it or decline it.

**Comment by waciumawanjohi** [comment]
@oNjEncUREn Totally reasonable comment. I will say that sadly this repo was functionally abandoned for all of that time. It has only been 29 days since I merged in v2 and took responsibility for the Data Science repo. I've neither closed nor merged this PR because I don't yet have a framework for evaluating suggestions for the extras sections.

You have my promise that I won't allow this PR to languish for another 3 years!✋

**Comment by oNjEncUREn** [comment]
No worries @waciumawanjohi  I completely understand where you're coming from trying to manage all this stuff.  I think as part of these different options (CS, DS, math, etc.) from OSSU, we need to develop solid issue / PR rules so we don't let things hang around longer than they should.  I'm hoping to help all this as much as possible.

**Comment by waciumawanjohi** [comment]
OSSU:CS has [contributing guidelines](https://github.com/ossu/computer-science/blob/master/CONTRIBUTING.md). I hadn't realized until today that I didn't port those over to OSSU:DS. I'll take care of that in the near future.

That will certainly help. There is also the question of, "What is the extras section for?" I don't have a go-to answer for that question. It's something that OSSU will have to deliberate on (but I'll say right now, it's a low priority question).

**Comment by waciumawanjohi** [comment]
Closing this PR for lack of information on why these books were chosen. Feel free to open an issue to discuss the books, their quality, and their alignment with the curriculum.

**Pull request closed without merging**
