### PR TITLE
Bring recent changes from CS repo, improve organization and add info about Final Project

### PR DESCRIPTION
**Pull request by pulkitkrishna00**
This PR does the following things:

- Remove outdated materials like Trello board and add warning about them
- Remove newsletter link
-  Mark the Py4E course link as link and fix CS50P discord link
- Add Intro CS coursepage
- Remove PROJECTS.md file (which was not linked in the README in this repo)
- Add information about final project and what to do after completing this curriculum (taken from CS repo)
- Improve the organization of the README, modelling it after the CS curriculum README.

### CODE REVIEW

**Comment by samarskii** [comment]
Maybe instead of deleting Projects.md we should invent something and add some basic and advanced projects to it?

**Comment by pulkitkrishna00** [comment]
> Maybe instead of deleting Projects.md we should invent something and add some basic and advanced projects to it?

It can be a good thing, but is it required? There is already a specialization file, which lists specializations which end with a capstone project. Anyway, I think that is out of scope of this PR, and the file can be easily added back in future if someone wants to undertake the job of finding/inventing projects. If people think it is better to leave the file, I don't have any problem reverting that commit.

**Comment by pulkitkrishna00** [comment]
Additionally, I don't think that is the purpose of the PROJECTS.md file. As written in that file, it lists

> Projects created by OSSU's students for each course of our [Data Science](https://github.com/open-source-society/data-science) curriculum.

The CS repo had a similar file, which was recently removed in a pull request by waciuma: ossu/computer-science#1227

**Comment by samarskii** [comment]
> Additionally, I don't think that is the purpose of the PROJECTS.md file. As written in that file, it lists
> 
> > Projects created by OSSU's students for each course of our [Data Science](https://github.com/open-source-society/data-science) curriculum.
> 
> The CS repo had a similar file, which was recently removed in a pull request by waciuma: [ossu/computer-science#1227](https://github.com/ossu/computer-science/pull/1227)

Sadly, but you are right and this was removed even in CS repo.

I am personally going through this path but thinking that it's lack some good project or even ideas for young data scientists to do projects.

**Pull request closed without merging**
